site_name: CIS Controls Assessment Specification

nav:
  - Home: index.md
  - Source:
    - Control 1: Control-1.md
    # - Control 2: Control-2.md
    # - Control 3: Control-3.md
    # - Control 4: Control-4.md
    # - Control 5: Control-5.md
    # - Control 6: Control-6.md
    # - Control 7: Control-7.md
    # - Control 8: Control-8.md
    # - Control 9: Control-9.md
    # - Control 10: Control-10.md
    # - Control 11: Control-11.md
    # - Control 12: Control-12.md
    # - Control 13: Control-13.md
    # - Control 14: Control-14.md
    # - Control 15: Control-15.md
    # - Control 16: Control-16.md
    # - Control 17: Control-17.md
    # - Control 18: Control-18.md
    # - Control 19: Control-19.md
    # - Control 20: Control-20.md
theme:
  name: readthedocs